### ISSUE TITLE
Writing Safer Code with Swift

### ISSUE THREAD

**Issue by bryanburgers** [sfdevs/meetups#4]
I would love to learn about Swift.

Some thing that could be covered in a talk about this
- What's going on here?
- Why is it so popular all of a sudden?
- How is it better than my favorite language?
- Is Apple really being open about it?
## Things we need to make this talk happen
- [x] Speaker: @Gagege 
- [x] Venue: Raven Training Center
- [x] Date: June 7, 2016
- [x] Get summary text from speaker
- [x] Create meetup.com event

**Comment by Gagege** [comment]
I've been using Swift and Kotlin (simultanious iOS and Android development) for the past year. They are very similar languages. I've also been using C# for server-side stuff at the same time. On the surface, Swift and C# look similar, but the differences between them are pretty stark. There's a lot to talk about there.

If someone has more experience than I do with Swift, I'd love to hear a talk from them. Otherwise, I'd be interested in giving the talk myself.

**Comment by bryanburgers** [comment]
Frankly, this sounds fascinating and I would kind of love to hear all about it. Do you think you could talk about all of that stuff in June or July?

**Comment by Gagege** [comment]
That sounds good. I'll be around on SF Devs Slack in the mean time (I'm dactou). Do you know about how many minutes I should plan on having?

**Comment by charwood** [comment]
I'm not adept in any of those languages but that sounds like a great talk that I'd attend the heck out of.  I think others at Zuercher would be interested as well.  Thanks for volunteering, Gage.

**Comment by bryanburgers** [comment]
@Gagege Typically 45–60 minutes, but as short as 30 or as long as 90 are OK.

**Comment by bryanburgers** [comment]
@Gagege Can you provide a title and a short summary of your talk, so we can promote it? Good examples would be http://www.meetup.com/sfdevs/events/227140442/ and http://www.meetup.com/sfdevs/events/225072098/.

**Comment by Gagege** [comment]
> ## Mobile Development With Swift and Kotlin
> 
> Have you ever wanted to get into mobile development but were scared off by the programming languages involved? Do you wish you could use something other than Java or Objective-C to develop in iOS or Android's native frameworks?
> 
> In recent years, both of those platforms have gained a few more viable options. We'll be taking a look at two of them, Swift for iOS and Kotlin for Android. These languages provide a lot in relation to the ease of mobile development, but they really shine as general purpose OO languages. They allow you to be more certain that, if your code compiles, it will probably run without exception. If you're used to writing server-side code in C# or Java, you'll be able to easily see the advantages of Swift or Kotlin.
> 
> We'll also look at some reasons to _not_ use Swift and Kotlin, and some powerful features you might be better off avoiding at first.

Is that kind of what you were thinking? If you'd rather, I can make it more Swift-y and dive in deep into that language by itself.

**Comment by sclarson** [comment]
I'd personally be more interested in just swift. Not opposed to also doing something on Kotlin at a later date.

**Comment by bryanburgers** [comment]
Meetup event created: http://www.meetup.com/sfdevs/events/231096032/

**Comment by Gagege** [comment]
I've decided to refocus the topic. I think the original topic was too broad. What I'd really like to do is explain the real reasons why _I_ use Swift, instead of say, Objective-C or Javascript, for mobile development. In the future I could do a "Writing Safer Code with Kotlin" talk, if there's any interest.

So, here's my new title and description:

# Writing Safer Code with Swift

A lot of the languages we use are extremely flexible and powerful. C# and Java allow you to write complex code that does a lot of things. They let you get stuff done, but they can also get you into a lot of trouble.

A few new languages have appeared in the last few years that are recognizing the importance of _protecting programmers from themselves_ while remaining flexible and powerful. We'll be taking a look at one of these languages, Swift.

Swift is an open source object oriented programming language that borrows heavily from the ML family of functional languages, such as F# and Haskell.

We'll talk about the ways Swift can make your programs less complex and more safe, and the ways you can still mess up, by writing clever, ie. bad, code.

**Comment by bryanburgers** [comment]
I updated the meetup event.
